export * as permissionService from "./permission.service";
export * as roleService from "./role.service";
export * as postService from "./post.service";
export * as commentService from "./comment.service";
export * as childrenPitchService from "./chirldrenPitch.service";
export * as shiftModelService from "./shift.service";
export * as locationService from "./location.service";
export * as pitchService from "./pitch.service";
export * as feedbackService from "./feedback.service";
